# -*- coding: utf-8 -*-
"""changeagent

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LwQ0kAXh47eTfiR35cIt4gou3HiqMbtR
"""

import pandas as pd
import numpy as np
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.preprocessing import LabelEncoder
import joblib
import warnings; warnings.filterwarnings('ignore')


df = pd.read_excel('MCRDatasetFin.xlsx')

df['Date'] = pd.to_datetime(df['Date'])
df = df.sort_values(['RegionName', 'Date']).reset_index(drop=True)


upper = df['AveragePrice'].quantile(0.99)
df = df[df['AveragePrice'] < upper]



df['year'] = df['Date'].dt.year
df['month'] = df['Date'].dt.month
df['quarter'] = df['Date'].dt.quarter
df['time_idx'] = (df['year'] - 1995) * 12 + df['month']


df['sin_month'] = np.sin(2 * np.pi * df['month'] / 12)
df['cos_month'] = np.cos(2 * np.pi * df['month'] / 12)


le = LabelEncoder()
df['region_enc'] = le.fit_transform(df['RegionName'])


for lag in [1, 3, 6, 12]:
    df[f'price_lag_{lag}'] = (
        df.groupby('RegionName')['AveragePrice'].shift(lag)
    )


df['rolling_avg_12'] = (
    df.groupby('RegionName')['AveragePrice']
      .transform(lambda x: x.rolling(12).mean().shift(1))
)


df['yoy_change'] = (
    df.groupby('RegionName')['AveragePrice']
      .pct_change(12)
)


df['price_trend_3m'] = df['price_lag_1'] - df['price_lag_3']
df['price_trend_12m'] = df['price_lag_1'] - df['price_lag_12']


df['lag_ratio_1_12'] = df['price_lag_1'] / df['price_lag_12']
df['volume_price_interaction'] = df['SalesVolume'] * df['price_lag_1']


df['price_band'] = pd.qcut(df['AveragePrice'], q=5, labels=False, duplicates='drop')

df = df.replace([np.inf, -np.inf], np.nan)
df = df.dropna()


FEATURES = [
    'region_enc', 'year', 'month', 'quarter', 'time_idx',
    'sin_month', 'cos_month',
    'SalesVolume',
    'price_lag_1', 'price_lag_3', 'price_lag_6', 'price_lag_12',
    'rolling_avg_12', 'yoy_change',
    'price_trend_3m', 'price_trend_12m',
    'lag_ratio_1_12', 'volume_price_interaction',
    'price_band'
]

TARGET = 'AveragePrice'


split_date = '2023-01-01'

train = df[df['Date'] < split_date]
test  = df[df['Date'] >= split_date]

X_train, y_train = train[FEATURES], train[TARGET]
X_test, y_test   = test[FEATURES], test[TARGET]


y_train_log = np.log1p(y_train)
y_test_log  = np.log1p(y_test)


weights = y_train / y_train.mean()


model = XGBRegressor(
    n_estimators=1800,
    learning_rate=0.025,
    max_depth=7,
    subsample=0.85,
    colsample_bytree=0.85,
    min_child_weight=3,
    gamma=1,
    reg_alpha=0.5,
    reg_lambda=2,
    early_stopping_rounds=50,
    eval_metric='rmse',
    random_state=42,
    n_jobs=-1
)

model.fit(
    X_train,
    y_train_log,
    sample_weight=weights,
    eval_set=[(X_test, y_test_log)],
    verbose=100
)


preds_log = model.predict(X_test)
preds = np.expm1(preds_log)


preds = np.clip(preds, 50000, 500000)


mae  = mean_absolute_error(y_test, preds)
rmse = np.sqrt(mean_squared_error(y_test, preds))
mape = np.mean(np.abs((y_test - preds) / y_test)) * 100

print(f"MAE:  £{mae:,.0f}")
print(f"RMSE: £{rmse:,.0f}")
print(f"MAPE: {mape:.2f}%")


joblib.dump(model, 'mcr_model.joblib')
joblib.dump(le, 'region_encoder.joblib')
df.to_csv("processed_data.csv", index=False)

print("Model saved!")