# -*- coding: utf-8 -*-
"""fastapichange

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tlpKzsIMrfyVRZquMCdkFRvsn9S3V8qp
"""

from fastapi import FastAPI
import joblib
import pandas as pd
import numpy as np

app = FastAPI()

model = joblib.load("mcr_model.joblib")
le    = joblib.load("region_encoder.joblib")
df    = pd.read_csv("processed_data.csv")
df["Date"] = pd.to_datetime(df["Date"])

FEATURES = [
    'region_enc', 'year', 'month', 'quarter', 'time_idx',
    'sin_month', 'cos_month',
    'SalesVolume',
    'price_lag_1', 'price_lag_3', 'price_lag_6', 'price_lag_12',
    'rolling_avg_12', 'yoy_change',
    'price_trend_3m', 'price_trend_12m',
    'lag_ratio_1_12', 'volume_price_interaction',
    'price_band'
]

@app.get("/")
def home():
    return {"message": "This API currently running"}

@app.post("/predict")
def predict(data: dict):


    try:
        region = data["region"]
        date   = pd.to_datetime(data["date"])
        budget = float(data["budget"]) if data.get("budget") else None
    except:
        return {"error": "Invalid input format"}

    if region not in df["RegionName"].unique():
        return {"error": "Region not found"}

    region_df = df[df["RegionName"] == region].sort_values("Date")
    latest    = region_df[region_df["Date"] < date].tail(1)

    if latest.empty:
        return {"error": "Not enough historical data"}

    latest = latest.copy()
    latest["year"]      = date.year
    latest["month"]     = date.month
    latest["quarter"]   = (date.month - 1) // 3 + 1
    latest["time_idx"]  = (date.year - 1995) * 12 + date.month
    latest["sin_month"] = np.sin(2 * np.pi * latest["month"] / 12)
    latest["cos_month"] = np.cos(2 * np.pi * latest["month"] / 12)
    latest["region_enc"] = le.transform([region])[0]


    pred_log        = model.predict(latest[FEATURES])[0]
    predicted_price = float(np.clip(np.expm1(pred_log), 50000, 500000))


    return {
        "region":          region,
        "date":            str(date.date()),
        "predicted_price": round(predicted_price, 2),
        "budget":          budget,
        "last_price":      round(float(latest["price_lag_1"].values[0]), 2),
        "yoy_change":      round(float(latest["yoy_change"].values[0]), 4),
        "price_trend_3m":  round(float(latest["price_trend_3m"].values[0]), 2),
        "price_trend_12m": round(float(latest["price_trend_12m"].values[0]), 2),
    }
